// 100 real pages with the folder a person would expect. Used to score Jev's accuracy.
export const TABS: { url: string; expect: string }[] = [
  // Dev (10)
  { url: "https://github.com/microsoft/TypeScript", expect: "Dev" },
  { url: "https://github.com/facebook/react/issues", expect: "Dev" },
  { url: "https://stackoverflow.com/questions/tagged/typescript", expect: "Dev" },
  { url: "https://developer.chrome.com/docs/extensions/reference/api/tabGroups", expect: "Dev" },
  { url: "https://www.typescriptlang.org/docs/handbook/2/generics.html", expect: "Dev" },
  { url: "https://vitejs.dev/guide/", expect: "Dev" },
  { url: "https://nodejs.org/api/fs.html", expect: "Dev" },
  { url: "https://www.npmjs.com/package/puppeteer", expect: "Dev" },
  { url: "https://gitlab.com/explore/projects", expect: "Dev" },
  { url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise", expect: "Dev" },
  // Work (8)
  { url: "https://www.atlassian.com/software/jira", expect: "Work" },
  { url: "https://trello.com/", expect: "Work" },
  { url: "https://asana.com/", expect: "Work" },
  { url: "https://www.notion.so/product", expect: "Work" },
  { url: "https://calendar.google.com/", expect: "Work" },
  { url: "https://zoom.us/", expect: "Work" },
  { url: "https://linear.app/", expect: "Work" },
  { url: "https://www.figma.com/", expect: "Work" },
  // AI (8)
  { url: "https://claude.ai/", expect: "AI" },
  { url: "https://chatgpt.com/", expect: "AI" },
  { url: "https://gemini.google.com/", expect: "AI" },
  { url: "https://huggingface.co/models", expect: "AI" },
  { url: "https://www.perplexity.ai/", expect: "AI" },
  { url: "https://console.anthropic.com/", expect: "AI" },
  { url: "https://platform.openai.com/playground", expect: "AI" },
  { url: "https://www.midjourney.com/", expect: "AI" },
  // Learning (8)
  { url: "https://www.coursera.org/learn/machine-learning", expect: "Learning" },
  { url: "https://www.khanacademy.org/math/algebra", expect: "Learning" },
  { url: "https://www.udemy.com/topic/python/", expect: "Learning" },
  { url: "https://www.edx.org/learn/computer-science", expect: "Learning" },
  { url: "https://arxiv.org/abs/1706.03762", expect: "Learning" },
  { url: "https://www.freecodecamp.org/learn", expect: "Learning" },
  { url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/", expect: "Learning" },
  { url: "https://www.duolingo.com/", expect: "Learning" },
  // Reading (7)
  { url: "https://en.wikipedia.org/wiki/Alan_Turing", expect: "Reading" },
  { url: "https://medium.com/", expect: "Reading" },
  { url: "https://paulgraham.com/greatwork.html", expect: "Reading" },
  { url: "https://www.newyorker.com/culture", expect: "Reading" },
  { url: "https://substack.com/", expect: "Reading" },
  { url: "https://www.gutenberg.org/ebooks/1342", expect: "Reading" },
  { url: "https://aeon.co/essays", expect: "Reading" },
  // Video (8)
  { url: "https://www.youtube.com/", expect: "Video" },
  { url: "https://www.netflix.com/", expect: "Video" },
  { url: "https://www.twitch.tv/directory", expect: "Video" },
  { url: "https://vimeo.com/watch", expect: "Video" },
  { url: "https://www.primevideo.com/", expect: "Video" },
  { url: "https://www.hulu.com/", expect: "Video" },
  { url: "https://www.disneyplus.com/", expect: "Video" },
  { url: "https://www.imdb.com/chart/top/", expect: "Video" },
  // Music (6)
  { url: "https://open.spotify.com/", expect: "Music" },
  { url: "https://music.apple.com/", expect: "Music" },
  { url: "https://soundcloud.com/discover", expect: "Music" },
  { url: "https://bandcamp.com/", expect: "Music" },
  { url: "https://music.youtube.com/", expect: "Music" },
  { url: "https://www.last.fm/music", expect: "Music" },
  // Social (8)
  { url: "https://www.reddit.com/r/programming/", expect: "Social" },
  { url: "https://x.com/", expect: "Social" },
  { url: "https://www.linkedin.com/feed/", expect: "Social" },
  { url: "https://www.instagram.com/", expect: "Social" },
  { url: "https://www.facebook.com/", expect: "Social" },
  { url: "https://news.ycombinator.com/", expect: "Social" },
  { url: "https://www.threads.net/", expect: "Social" },
  { url: "https://bsky.app/", expect: "Social" },
  // News (8)
  { url: "https://www.bbc.com/news", expect: "News" },
  { url: "https://www.nytimes.com/", expect: "News" },
  { url: "https://www.reuters.com/", expect: "News" },
  { url: "https://www.theguardian.com/international", expect: "News" },
  { url: "https://apnews.com/", expect: "News" },
  { url: "https://www.cnn.com/", expect: "News" },
  { url: "https://www.aljazeera.com/", expect: "News" },
  { url: "https://timesofindia.indiatimes.com/", expect: "News" },
  // Shopping (8)
  { url: "https://www.amazon.com/", expect: "Shopping" },
  { url: "https://www.ebay.com/", expect: "Shopping" },
  { url: "https://www.etsy.com/", expect: "Shopping" },
  { url: "https://www.flipkart.com/", expect: "Shopping" },
  { url: "https://www.ikea.com/us/en/", expect: "Shopping" },
  { url: "https://www.bestbuy.com/", expect: "Shopping" },
  { url: "https://www.walmart.com/", expect: "Shopping" },
  { url: "https://www.target.com/", expect: "Shopping" },
  // Finance (7)
  { url: "https://www.paypal.com/", expect: "Finance" },
  { url: "https://finance.yahoo.com/", expect: "Finance" },
  { url: "https://www.coinbase.com/", expect: "Finance" },
  { url: "https://www.chase.com/", expect: "Finance" },
  { url: "https://www.robinhood.com/", expect: "Finance" },
  { url: "https://www.investopedia.com/", expect: "Finance" },
  { url: "https://wise.com/", expect: "Finance" },
  // Travel (7)
  { url: "https://www.booking.com/", expect: "Travel" },
  { url: "https://www.airbnb.com/", expect: "Travel" },
  { url: "https://www.google.com/maps", expect: "Travel" },
  { url: "https://www.expedia.com/", expect: "Travel" },
  { url: "https://www.skyscanner.com/", expect: "Travel" },
  { url: "https://www.tripadvisor.com/", expect: "Travel" },
  { url: "https://www.kayak.com/flights", expect: "Travel" },
  // Email & Chat (7)
  { url: "https://mail.google.com/", expect: "Email & Chat" },
  { url: "https://outlook.live.com/", expect: "Email & Chat" },
  { url: "https://web.whatsapp.com/", expect: "Email & Chat" },
  { url: "https://slack.com/", expect: "Email & Chat" },
  { url: "https://discord.com/", expect: "Email & Chat" },
  { url: "https://web.telegram.org/", expect: "Email & Chat" },
  { url: "https://proton.me/mail", expect: "Email & Chat" },
];
